name: build-gui
on:
  workflow_call:
    inputs:
      version_override:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      version_override:
        type: string
        description: Version override. If not given, will use the default value in configure.ac.
        default: ""

jobs:
  build-gui-linux:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install dependencies
        run: python3 -m pip install -r GUI/requirements.dev.txt -r GUI/requirements.txt
      - name: build GUI files
        run: |
          test -n "${{ inputs.version_override }}" \
            && VERSION_OVERRIDE_ARG="--version-override=${{ inputs.version_override }}"
          cd GUI && python3 buildtool.py build $VERSION_OVERRIDE_ARG
      - name: Archive generated GUI files
        uses: actions/upload-artifact@v4
        with:
          name: cmake-linux-gui-files
          path: |
            GUI/xasyicons
            GUI/xasyqtui
            GUI/xasyversion
  build-gui-windows:
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install dependencies
        run: python.exe -m pip install -r GUI/requirements.dev.txt -r GUI/requirements.txt
      - name: build GUI files
        shell: pwsh
        run: |
          Push-Location GUI
          if ("${{ inputs.version_override }}")
          {
            $version_override_arg="--version-override=${{ inputs.version_override }}"
          }
          python.exe buildtool.py build $version_override_arg
          Pop-Location
      - name: Archive generated GUI files
        uses: actions/upload-artifact@v4
        with:
          name: cmake-windows-gui-files
          path: |
            GUI/xasyicons
            GUI/xasyqtui
            GUI/xasyversion
